include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.g.dart

linter:
  rules:
    - always_use_package_imports
    - require_trailing_commas
    - always_put_required_named_parameters_first
    - prefer_const_constructors
    - sort_constructors_first
    - prefer_expression_function_bodies
